-- ============================================================
-- CareerOS Migration 030: Platform Posts & Agent Content Generations
-- ============================================================

-- Table to store content generated by Agent 4 pending user approval
CREATE TABLE IF NOT EXISTS agent_content_generations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    run_id TEXT NOT NULL,
    generated_content TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table to store final approved content posted to the platform
CREATE TABLE IF NOT EXISTS platform_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    posted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_generation_id UUID REFERENCES agent_content_generations(id) ON DELETE SET NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_agent_content_generations_user_id ON agent_content_generations(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_content_generations_status ON agent_content_generations(status);
CREATE INDEX IF NOT EXISTS idx_platform_posts_user_id ON platform_posts(user_id);

-- Row Level Security (RLS)
ALTER TABLE agent_content_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own generated content"
    ON agent_content_generations FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view and manage their own platform posts"
    ON platform_posts FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
